
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev   # <== Dockerfile spécial dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
