services:
  php:
    image: php:8.2-apache
    container_name: symfony-app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    restart: always
    command: >
      bash -c "apt-get update && 
               apt-get install -y git unzip libzip-dev && 
               docker-php-ext-install zip pdo pdo_mysql && 
               curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && 
               chown -R www-data:www-data /var/www/html &&
               chmod -R 755 /var/www/html &&
               a2enmod rewrite &&
               echo '<VirtualHost *:80>
                    DocumentRoot /var/www/html/public
                    DirectoryIndex /index.php
                    <Directory /var/www/html/public>
                        AllowOverride All
                        Require all granted
                        FallbackResource /index.php
                    </Directory>
               </VirtualHost>' > /etc/apache2/sites-available/000-default.conf &&
               apache2-foreground"
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: myfirstloizir
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: myfirstloizir
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
