services:
  php:
    image: php:8.2-apache
    container_name: symfony-app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    restart: always
    command: >
      bash -c "apt-get update && 
               apt-get install -y git unzip libzip-dev && 
               docker-php-ext-install zip pdo pdo_mysql && 
               curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && 
               a2enmod rewrite && 
               apache2-foreground"
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: myfirstloizir
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  react:
    image: node:18
    container_name: react-app
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "if [ ! -f package.json ]; then 
             npx create-react-app . --legacy-peer-deps &&
             npm install web-vitals @babel/plugin-proposal-private-property-in-object --legacy-peer-deps;
             fi &&
             npm start -- --host 0.0.0.0"
    environment:
      - WDS_SOCKET_HOST=0.0.0.0
      - WATCHPACK_POLLING=true

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: myfirstloizir
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
